[workspace]
members = ["cli", "macros", "sendfile", "sendfile-ffi-bindings"]
resolver = "2"

[workspace.dependencies]
aes-gcm = "0.9.4"
anyhow = "1.0.57"
async-trait = "0.1.52"
backoff = "0.4.0"
base64 = "0.13.0"
bytes = "1.1.0"
cfg-if = "1.0.0"
clap = "3.0.10"
crossbeam = "0.8.1"
crossbeam-utils = "0.8.8"
datachannel = "0.7.3"
derive_more = "0.99.17"
futures = "0.3.21"
getrandom = "0.2"
gloo-timers = "0.2.4"
hkdf = "0.12.3"
http = "0.2.6"
indicatif = "0.17.0-rc.10"
instant = "0.1.12"
js-sys = "0.3.56"
log = "0.4.14"
num_enum = "0.5.7"
pin-project = "1.0.10"
pretty_env_logger = "0.4.0"
proc-macro-error = "1.0.4"
proc-macro2 = { version = "1.0.36", default-features = false }
prost = "0.9.0"
prost-build = "0.9.0"
quote = "1.0.17"
rand = "0.8.4"
reqwest = { git = "https://github.com/privacyresearchgroup/reqwest.git", branch = "wasm-streaming" }
scopeguard = "1.1.0"
sendfile = { path = "sendfile" }
sendfile-macros = { path = "macros" }
serde = "1.0.137"
serde_json = "1.0.75"
sha2 = "0.10.2"
syn = "1.0.90"
tempfile = "3.3.0"
thiserror = "1.0.30"
tokio = "1.16.1"
tokio-stream = "0.1"
tokio-tungstenite = "0.16.1"
tokio-util = "0.7.0"
toml = "0.5.9"
tungstenite = "0.16.0"
uniffi = "0.18.0"
uniffi_bindgen = "0.18.0"
uniffi_build = "0.18.0"
url = "2.2.2"
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.29"
web-sys = "0.3.56"
webrtc-sdp = "0.3.9"
zeroize = "1.5"

# Only use the strip option for sendfile-cli, since it is only stable since Cargo 1.59.0, and Cargo before that will
# then fail to compile _any_ of our workspace packages with any profile if we specify it globally.
[profile.distribution.package.sendfile-cli]
strip = true

[profile.distribution]
inherits = "release"
opt-level = "s"
codegen-units = 1
lto = true
