[workspace]
members = ["cli", "macros", "sendfile", "sendfile-ffi-bindings"]
resolver = "2"

[workspace.dependencies]
aes-gcm = "0.9.4"
anyhow = "1.0.104"
async-trait = "0.1.92"
backoff = "0.4.0"
base64 = "0.23.1"
bytes = "1.12.1"
cfg-if = "1.0.5"
clap = "3.2.25"
crossbeam = "0.8.5"
crossbeam-utils = "0.8.23"
datachannel = "0.16.1"
derive_more = { version = "2.1.1", features = ["deref", "from"] }
futures = "0.3.34"
getrandom = "0.2"
gloo-timers = "0.2.6"
hkdf = "0.12.4"
http = "0.2.12"
indicatif = "0.17.11"
instant = "0.1.13"
js-sys = "0.3.105"
log = "0.4.34"
num_enum = "0.7.6"
pin-project = "1.1.13"
pretty_env_logger = "0.4.0"
proc-macro2 = { version = "1.0.107", default-features = false }
prost = "0.9.0"
prost-build = "0.9.0"
quote = "1.0.47"
rand = "0.8.8"
reqwest = { git = "https://github.com/privacyresearchgroup/reqwest.git", branch = "wasm-streaming" }
scopeguard = "1.2.0"
sendfile = { path = "sendfile" }
sendfile-macros = { path = "macros" }
serde = "1.0.229"
serde_json = "1.0.151"
sha2 = "0.10.9"
syn = "3.0.6"
tempfile = "3.27.0"
thiserror = "2.0.20"
tokio = "1.53.1"
tokio-stream = "0.1"
tokio-tungstenite = "0.16.1"
tokio-util = "0.7.19"
toml = "0.5.11"
tungstenite = "0.16.0"
uniffi = "0.18.0"
uniffi_bindgen = "0.18.0"
uniffi_build = "0.18.0"
url = "2.5.8"
wasm-bindgen = "0.2.128"
wasm-bindgen-futures = "0.4.78"
web-sys = "0.3.105"
webrtc-sdp = "0.3.15"
zeroize = "1.9"

# Only use the strip option for sendfile-cli, since it is only stable since Cargo 1.59.0, and Cargo before that will
# then fail to compile _any_ of our workspace packages with any profile if we specify it globally.
[profile.distribution.package.sendfile-cli]
strip = true

[profile.distribution]
inherits = "release"
opt-level = "s"
codegen-units = 1
lto = true
