#!/usr/bin/env bash

# Transfer `example-file` from a local upload client to a local download client.
#
# Usage Examples:
#
#     # default settings
#     scripts/round-trip
#
#     # disable p2p on uploading client
#     UPLOAD_OPTIONS="--no-p2p" scripts/round-trip
#
#     # disable p2p on downloading client
#     DOWNLOAD_OPTIONS="--no-p2p" scripts/round-trip
#
#     # Incompatible settings like this are expected to time out
#     DOWNLOAD_OPTIONS="--no-relay" UPLOAD_OPTIONS="--no-p2p" scripts/round-trip

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR/..
RUST_LOG=sendfile=info cargo run -- send example-file $UPLOAD_OPTIONS | tee >(export RUST_LOG=sendfile=info; head -n 1 | sed "s/.*download at: //" | xargs cargo run -- receive $DOWNLOAD_OPTIONS 2>&1 | sed "s/^/[recipient] /")
