name: gh-pages
on:
  push:
    branches:
      - master
      - edocs

defaults:
  run:
    shell: bash
jobs:
  gh-pages:
    name:    gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: compile sources
        run: rebar3 compile

      - name: generate edocs
        run:  |
          apps=_build/default/lib
          for app in $(cd $apps; ls -1); do
            echo building edocs for $app
            ERL_LIBS=$apps erl -noshell -run edoc_run application $app '[{app_default, "/sendfile"}, {preprocess, true}, {private, true}, {todo, true}, {sort_functions, false}, {pretty_printer, erl_pp}]'
            mkdir -p docs/$app
            mv $apps/$app/doc docs/$app/
          done
          mv docs/sendfile/doc/* docs/
          rm -r docs/sendfile

      - name: force push docs to gh-pages branch
        run: |
          git config user.name "Github CI -- gh-pages"
          git config user.email "<>"
          git add -f docs
          git commit -m "render edocs"
          git push -f origin HEAD:gh-pages

      - name: run integration tests (common_test)
        run:  |
          rebar3 ct || true
          mv _build/test/logs docs/ct

      - name: force push integration test reports to gh-pages branch
        run: |
          git add -f docs
          git commit -m "add common_test reports"
          git push -f origin HEAD:gh-pages
