%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.5

-ifndef(sendfile_websocket_protocol).
-define(sendfile_websocket_protocol, true).

-define(sendfile_websocket_protocol_gpb_version, "4.19.5").

-ifndef('SENDFILE_WEBSOCKET_PROTOCOL_WEB_SOCKET_MESSAGE_PB_H').
-define('SENDFILE_WEBSOCKET_PROTOCOL_WEB_SOCKET_MESSAGE_PB_H', true).
-record(sendfile_websocket_protocol_web_socket_message,
        {inner                  :: {rtc_signaling, sendfile_websocket_protocol:sendfile_websocket_protocol_rtc_signaling_message()} | {upload_data_ack, sendfile_websocket_protocol:sendfile_websocket_protocol_upload_data_ack()} | undefined % oneof
        }).
-endif.

-ifndef('SENDFILE_WEBSOCKET_PROTOCOL_RTC_SIGNALING_MESSAGE_PB_H').
-define('SENDFILE_WEBSOCKET_PROTOCOL_RTC_SIGNALING_MESSAGE_PB_H', true).
-record(sendfile_websocket_protocol_rtc_signaling_message,
        {inner                  :: {ice_candidate, sendfile_websocket_protocol:sendfile_websocket_protocol_ice_candidate()} | {session_description, sendfile_websocket_protocol:sendfile_websocket_protocol_session_description()} | undefined % oneof
        }).
-endif.

-ifndef('SENDFILE_WEBSOCKET_PROTOCOL_ICE_CANDIDATE_PB_H').
-define('SENDFILE_WEBSOCKET_PROTOCOL_ICE_CANDIDATE_PB_H', true).
-record(sendfile_websocket_protocol_ice_candidate,
        {candidate = <<>>       :: unicode:chardata() | undefined, % = 1, optional
         mid = <<>>             :: unicode:chardata() | undefined % = 2, optional
        }).
-endif.

-ifndef('SENDFILE_WEBSOCKET_PROTOCOL_SESSION_DESCRIPTION_PB_H').
-define('SENDFILE_WEBSOCKET_PROTOCOL_SESSION_DESCRIPTION_PB_H', true).
-record(sendfile_websocket_protocol_session_description,
        {sdp = <<>>             :: unicode:chardata() | undefined, % = 1, optional
         sdp_type = 'ANSWER'    :: 'ANSWER' | 'OFFER' | 'PRANSWER' | 'ROLLBACK' | integer() | undefined % = 2, optional, enum sendfile.websocket.protocol.SessionDescriptionType
        }).
-endif.

-ifndef('SENDFILE_WEBSOCKET_PROTOCOL_UPLOAD_DATA_ACK_PB_H').
-define('SENDFILE_WEBSOCKET_PROTOCOL_UPLOAD_DATA_ACK_PB_H', true).
-record(sendfile_websocket_protocol_upload_data_ack,
        {offset = 0             :: non_neg_integer() | undefined % = 1, optional, 64 bits
        }).
-endif.

-endif.
