[package]
name = "glopfile-cli"
version = "0.2.2"
edition = "2021"

# The package is glopfile-cli so it does not collide with the client library;
# the binary is what people type.
[[bin]]
name = "glopfile"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
clap = { workspace = true, features = ["derive"] }
crossbeam.workspace = true
indicatif = { workspace = true, features = ["improved_unicode"] }
pretty_env_logger.workspace = true
glopfile.workspace = true
url.workspace = true
