global(WorkDirectory="/home/erlang/rsyslog-spool"
       DefaultNetstreamDriver="gtls"
       DefaultNetstreamDriverCAFile="/etc/ssl/certs/ca-certificates.crt")

module(load="imuxsock" SysSock.Use="off")
input(type="imuxsock" Socket="/home/erlang/rsyslog-sock" CreatePath="on")

action(type="omfwd"
       Target="logs.papertrailapp.com" Port="47008" Protocol="tcp"
       StreamDriver="gtls"
       StreamDriverMode="1"
       StreamDriverAuthMode="x509/name"
       StreamDriverPermittedPeers="*.papertrailapp.com"
       Action.ResumeRetryCount="-1"
       Action.ResumeInterval="2"
       Queue.Type="linkedlist"
       Queue.FileName="papertrailqueue"
       Queue.Size="10000"
       Queue.HighWaterMark="8000"
       Queue.MaxDiskSpace="10m"
       Queue.TimeoutEnqueue="0"
       Queue.DiscardSeverity="0")
