accepted = [
    "MIT",
    "Apache-2.0",
    "AGPL-3.0",
    "BSD-3-Clause",
    "MPL-2.0",
    "LGPL-2.1",
]

targets = [
    "x86_64-apple-ios",
    "aarch64-apple-ios",
]

ignore-build-dependencies = true
ignore-dev-dependencies   = true
