name: test
on: [push]

defaults:
  run:
    shell: bash
jobs:
  build-and-test-native:
    name: build-and-test-native
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: cargo check
        run:  cargo check --verbose

      - name: cargo build
        run:  cargo build --verbose

      - name: cargo test
        run:  |
          TEST_SENDFILE_API_ENDPOINT=${{ secrets.TEST_SENDFILE_API_ENDPOINT }} \
          TEST_SENDFILE_DOWNLOAD_ENDPOINT=${{ secrets.TEST_SENDFILE_DOWNLOAD_ENDPOINT }} \
          cargo test --verbose

      - name: cargo clippy
        run:  cargo clippy

  build-web:
    name: build-web
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: install rust target wasm32-unknown-unknown
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: cargo check
        run:  cargo check --verbose --lib --target wasm32-unknown-unknown

      - name: cargo build
        run:  cargo build --verbose --lib --target wasm32-unknown-unknown

      - name: cargo clippy
        run:  cargo clippy --lib --target wasm32-unknown-unknown
