// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(SendfileRustFFI)
import SendfileRustFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_Sendfile_d234_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_Sendfile_d234_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a libray of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        // TODO: This copies the buffer. Can we read directly from a
        // Rust buffer?
        self.init(bytes: rustBuffer.data!, count: Int(rustBuffer.len))
    }
}

// A helper class to read values out of a byte buffer.
fileprivate class Reader {
    let data: Data
    var offset: Data.Index

    init(data: Data) {
        self.data = data
        self.offset = 0
    }

    // Reads an integer at the current offset, in big-endian order, and advances
    // the offset on success. Throws if reading the integer would move the
    // offset past the end of the buffer.
    func readInt<T: FixedWidthInteger>() throws -> T {
        let range = offset..<offset + MemoryLayout<T>.size
        guard data.count >= range.upperBound else {
            throw UniffiInternalError.bufferOverflow
        }
        if T.self == UInt8.self {
            let value = data[offset]
            offset += 1
            return value as! T
        }
        var value: T = 0
        let _ = withUnsafeMutableBytes(of: &value, { data.copyBytes(to: $0, from: range)})
        offset = range.upperBound
        return value.bigEndian
    }

    // Reads an arbitrary number of bytes, to be used to read
    // raw bytes, this is useful when lifting strings
    func readBytes(count: Int) throws -> Array<UInt8> {
        let range = offset..<(offset+count)
        guard data.count >= range.upperBound else {
            throw UniffiInternalError.bufferOverflow
        }
        var value = [UInt8](repeating: 0, count: count)
        value.withUnsafeMutableBufferPointer({ buffer in
            data.copyBytes(to: buffer, from: range)
        })
        offset = range.upperBound
        return value
    }

    // Reads a float at the current offset.
    @inlinable
    func readFloat() throws -> Float {
        return Float(bitPattern: try readInt())
    }

    // Reads a float at the current offset.
    @inlinable
    func readDouble() throws -> Double {
        return Double(bitPattern: try readInt())
    }

    // Indicates if the offset has reached the end of the buffer.
    @inlinable
    func hasRemaining() -> Bool {
        return offset < data.count
    }
}

// A helper class to write values into a byte buffer.
fileprivate class Writer {
    var bytes: [UInt8]
    var offset: Array<UInt8>.Index

    init() {
        self.bytes = []
        self.offset = 0
    }

    func writeBytes<S>(_ byteArr: S) where S: Sequence, S.Element == UInt8 {
        bytes.append(contentsOf: byteArr)
    }

    // Writes an integer in big-endian order.
    //
    // Warning: make sure what you are trying to write
    // is in the correct type!
    func writeInt<T: FixedWidthInteger>(_ value: T) {
        var value = value.bigEndian
        withUnsafeBytes(of: &value) { bytes.append(contentsOf: $0) }
    }

    @inlinable
    func writeFloat(_ value: Float) {
        writeInt(value.bitPattern)
    }

    @inlinable
    func writeDouble(_ value: Double) {
        writeInt(value.bitPattern)
    }
}

// Protocol for types that transfer other types across the FFI. This is
// analogous go the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: Reader) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: Writer)
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
    static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    static func lift(_ buf: RustBuffer) throws -> SwiftType {
        let reader = Reader(data: Data(rustBuffer: buf))
        let value = try read(from: reader)
        if reader.hasRemaining() {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    static func lower(_ value: SwiftType) -> RustBuffer {
          let writer = Writer()
          write(value, into: writer)
          return RustBuffer(bytes: writer.bytes)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_PANIC: Int8 = 2

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: {
        $0.deallocate()
        return UniffiInternalError.unexpectedRustCallError
    })
}

private func rustCallWithError<T, F: FfiConverter>
    (_ errorFfiConverter: F.Type, _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T
    where F.SwiftType: Error, F.FfiType == RustBuffer
    {
    try makeRustCall(callback, errorHandler: { return try errorFfiConverter.lift($0) })
}

private func makeRustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T, errorHandler: (RustBuffer) throws -> Error) throws -> T {
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    switch callStatus.code {
        case CALL_SUCCESS:
            return returnedVal

        case CALL_ERROR:
            throw try errorHandler(callStatus.errorBuf)

        case CALL_PANIC:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

// Public interface members begin here.


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Transport {
    
    case p2p
    case relay
    case both
}

fileprivate struct FfiConverterTypeTransport: FfiConverterRustBuffer {
    typealias SwiftType = Transport

    static func read(from buf: Reader) throws -> Transport {
        let variant: Int32 = try buf.readInt()
        switch variant {
        
        case 1: return .p2p
        
        case 2: return .relay
        
        case 3: return .both
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    static func write(_ value: Transport, into buf: Writer) {
        switch value {
        
        
        case .p2p:
            buf.writeInt(Int32(1))
        
        
        case .relay:
            buf.writeInt(Int32(2))
        
        
        case .both:
            buf.writeInt(Int32(3))
        
        }
    }
}


extension Transport: Equatable, Hashable {}


public protocol UploaderClientProtocol {
    func provisionFileFfi(path: String) throws -> NativeProvisionedFile
    func uploadProvisionedFileFfi(provisionedFile: NativeProvisionedFile) throws
    
}

public class UploaderClient: UploaderClientProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { ffi_Sendfile_d234_UploaderClient_object_free(pointer, $0) }
    }

    
    public static func newFfi(apiEndpoint: String, downloadEndpoint: String, transport: Transport) throws -> UploaderClient {
        return UploaderClient(unsafeFromRawPointer: try
    
    rustCallWithError(FfiConverterTypeSendfileError.self) {
    
    Sendfile_d234_UploaderClient_new_ffi(
        FfiConverterString.lower(apiEndpoint), 
        FfiConverterString.lower(downloadEndpoint), 
        FfiConverterTypeTransport.lower(transport), $0)
})
    }
    

    
    public func provisionFileFfi(path: String) throws -> NativeProvisionedFile {
        return try FfiConverterTypeNativeProvisionedFile.lift(
            try
    rustCallWithError(FfiConverterTypeSendfileError.self) {
    Sendfile_d234_UploaderClient_provision_file_ffi(self.pointer, 
        FfiConverterString.lower(path), $0
    )
}
        )
    }
    public func uploadProvisionedFileFfi(provisionedFile: NativeProvisionedFile) throws {
        try
    rustCallWithError(FfiConverterTypeSendfileError.self) {
    Sendfile_d234_UploaderClient_upload_provisioned_file_ffi(self.pointer, 
        FfiConverterTypeNativeProvisionedFile.lower(provisionedFile), $0
    )
}
    }
    
}


fileprivate struct FfiConverterTypeUploaderClient: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = UploaderClient

    static func read(from buf: Reader) throws -> UploaderClient {
        let v: UInt64 = try buf.readInt()
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    static func write(_ value: UploaderClient, into buf: Writer) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        buf.writeInt(UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    static func lift(_ pointer: UnsafeMutableRawPointer) throws -> UploaderClient {
        return UploaderClient(unsafeFromRawPointer: pointer)
    }

    static func lower(_ value: UploaderClient) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}

public protocol NativeProvisionedFileProtocol {
    func formattedDownloadUrlAndKey()  -> String
    
}

public class NativeProvisionedFile: NativeProvisionedFileProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { ffi_Sendfile_d234_NativeProvisionedFile_object_free(pointer, $0) }
    }

    

    
    public func formattedDownloadUrlAndKey()  -> String {
        return try! FfiConverterString.lift(
            try!
    rustCall() {
    
    Sendfile_d234_NativeProvisionedFile_formatted_download_url_and_key(self.pointer, $0
    )
}
        )
    }
    
}


fileprivate struct FfiConverterTypeNativeProvisionedFile: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = NativeProvisionedFile

    static func read(from buf: Reader) throws -> NativeProvisionedFile {
        let v: UInt64 = try buf.readInt()
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    static func write(_ value: NativeProvisionedFile, into buf: Writer) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        buf.writeInt(UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    static func lift(_ pointer: UnsafeMutableRawPointer) throws -> NativeProvisionedFile {
        return NativeProvisionedFile(unsafeFromRawPointer: pointer)
    }

    static func lower(_ value: NativeProvisionedFile) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}

public protocol DownloaderClientProtocol {
    func downloadIdFfi()  -> String
    func fetchMetaFfi() throws -> DownloadMeta
    func downloadFfi(meta: DownloadMeta, outputDir: String?, p2pTimeout: TimeInterval?) throws
    
}

public class DownloaderClient: DownloaderClientProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { ffi_Sendfile_d234_DownloaderClient_object_free(pointer, $0) }
    }

    
    public static func fromDownloadUrlFfi(downloadUrl: String, apiEndpoint: String, transport: Transport) throws -> DownloaderClient {
        return DownloaderClient(unsafeFromRawPointer: try
    
    rustCallWithError(FfiConverterTypeSendfileError.self) {
    
    Sendfile_d234_DownloaderClient_from_download_url_ffi(
        FfiConverterString.lower(downloadUrl), 
        FfiConverterString.lower(apiEndpoint), 
        FfiConverterTypeTransport.lower(transport), $0)
})
    }
    

    
    public func downloadIdFfi()  -> String {
        return try! FfiConverterString.lift(
            try!
    rustCall() {
    
    Sendfile_d234_DownloaderClient_download_id_ffi(self.pointer, $0
    )
}
        )
    }
    public func fetchMetaFfi() throws -> DownloadMeta {
        return try FfiConverterTypeDownloadMeta.lift(
            try
    rustCallWithError(FfiConverterTypeSendfileError.self) {
    Sendfile_d234_DownloaderClient_fetch_meta_ffi(self.pointer, $0
    )
}
        )
    }
    public func downloadFfi(meta: DownloadMeta, outputDir: String?, p2pTimeout: TimeInterval?) throws {
        try
    rustCallWithError(FfiConverterTypeSendfileError.self) {
    Sendfile_d234_DownloaderClient_download_ffi(self.pointer, 
        FfiConverterTypeDownloadMeta.lower(meta), 
        FfiConverterOptionString.lower(outputDir), 
        FfiConverterOptionDuration.lower(p2pTimeout), $0
    )
}
    }
    
}


fileprivate struct FfiConverterTypeDownloaderClient: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = DownloaderClient

    static func read(from buf: Reader) throws -> DownloaderClient {
        let v: UInt64 = try buf.readInt()
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    static func write(_ value: DownloaderClient, into buf: Writer) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        buf.writeInt(UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    static func lift(_ pointer: UnsafeMutableRawPointer) throws -> DownloaderClient {
        return DownloaderClient(unsafeFromRawPointer: pointer)
    }

    static func lower(_ value: DownloaderClient) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}

public protocol DownloadMetaProtocol {
    func fileMetaFfi()  -> FileMeta
    
}

public class DownloadMeta: DownloadMetaProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { ffi_Sendfile_d234_DownloadMeta_object_free(pointer, $0) }
    }

    

    
    public func fileMetaFfi()  -> FileMeta {
        return try! FfiConverterTypeFileMeta.lift(
            try!
    rustCall() {
    
    Sendfile_d234_DownloadMeta_file_meta_ffi(self.pointer, $0
    )
}
        )
    }
    
}


fileprivate struct FfiConverterTypeDownloadMeta: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = DownloadMeta

    static func read(from buf: Reader) throws -> DownloadMeta {
        let v: UInt64 = try buf.readInt()
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    static func write(_ value: DownloadMeta, into buf: Writer) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        buf.writeInt(UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    static func lift(_ pointer: UnsafeMutableRawPointer) throws -> DownloadMeta {
        return DownloadMeta(unsafeFromRawPointer: pointer)
    }

    static func lower(_ value: DownloadMeta) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}

public struct FileMeta {
    public var fileName: String
    public var fileSize: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(fileName: String, fileSize: UInt64) {
        self.fileName = fileName
        self.fileSize = fileSize
    }
}


extension FileMeta: Equatable, Hashable {
    public static func ==(lhs: FileMeta, rhs: FileMeta) -> Bool {
        if lhs.fileName != rhs.fileName {
            return false
        }
        if lhs.fileSize != rhs.fileSize {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(fileName)
        hasher.combine(fileSize)
    }
}


fileprivate struct FfiConverterTypeFileMeta: FfiConverterRustBuffer {
    fileprivate static func read(from buf: Reader) throws -> FileMeta {
        return try FileMeta(
            fileName: FfiConverterString.read(from: buf), 
            fileSize: FfiConverterUInt64.read(from: buf)
        )
    }

    fileprivate static func write(_ value: FileMeta, into buf: Writer) {
        FfiConverterString.write(value.fileName, into: buf)
        FfiConverterUInt64.write(value.fileSize, into: buf)
    }
}

public enum SendfileError {

    
    
    // Simple error enums only carry a message
    case ClientHttpErrorResponse(message: String)
    
    // Simple error enums only carry a message
    case ClientApiErrorResponse(message: String)
    
    // Simple error enums only carry a message
    case WebSocketClosed(message: String)
    
    // Simple error enums only carry a message
    case Io(message: String)
    
    // Simple error enums only carry a message
    case HttpClient(message: String)
    
    // Simple error enums only carry a message
    case RtcDataChannel(message: String)
    
    // Simple error enums only carry a message
    case WebSocketClient(message: String)
    
    // Simple error enums only carry a message
    case InvalidPeerMessage(message: String)
    
    // Simple error enums only carry a message
    case InvalidInput(message: String)
    
    // Simple error enums only carry a message
    case InvalidCipherKey(message: String)
    
    // Simple error enums only carry a message
    case Decrypt(message: String)
    
    // Simple error enums only carry a message
    case InvalidServerResponse(message: String)
    
    // Simple error enums only carry a message
    case Timeout(message: String)
    
}

fileprivate struct FfiConverterTypeSendfileError: FfiConverterRustBuffer {
    typealias SwiftType = SendfileError

    static func read(from buf: Reader) throws -> SendfileError {
        let variant: Int32 = try buf.readInt()
        switch variant {

        

        
        case 1: return .ClientHttpErrorResponse(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 2: return .ClientApiErrorResponse(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 3: return .WebSocketClosed(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 4: return .Io(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 5: return .HttpClient(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 6: return .RtcDataChannel(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 7: return .WebSocketClient(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 8: return .InvalidPeerMessage(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 9: return .InvalidInput(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 10: return .InvalidCipherKey(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 11: return .Decrypt(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 12: return .InvalidServerResponse(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 13: return .Timeout(
            message: try FfiConverterString.read(from: buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    static func write(_ value: SendfileError, into buf: Writer) {
        switch value {

        

        
        case let .ClientHttpErrorResponse(message):
            buf.writeInt(Int32(1))
            FfiConverterString.write(message, into: buf)
        case let .ClientApiErrorResponse(message):
            buf.writeInt(Int32(2))
            FfiConverterString.write(message, into: buf)
        case let .WebSocketClosed(message):
            buf.writeInt(Int32(3))
            FfiConverterString.write(message, into: buf)
        case let .Io(message):
            buf.writeInt(Int32(4))
            FfiConverterString.write(message, into: buf)
        case let .HttpClient(message):
            buf.writeInt(Int32(5))
            FfiConverterString.write(message, into: buf)
        case let .RtcDataChannel(message):
            buf.writeInt(Int32(6))
            FfiConverterString.write(message, into: buf)
        case let .WebSocketClient(message):
            buf.writeInt(Int32(7))
            FfiConverterString.write(message, into: buf)
        case let .InvalidPeerMessage(message):
            buf.writeInt(Int32(8))
            FfiConverterString.write(message, into: buf)
        case let .InvalidInput(message):
            buf.writeInt(Int32(9))
            FfiConverterString.write(message, into: buf)
        case let .InvalidCipherKey(message):
            buf.writeInt(Int32(10))
            FfiConverterString.write(message, into: buf)
        case let .Decrypt(message):
            buf.writeInt(Int32(11))
            FfiConverterString.write(message, into: buf)
        case let .InvalidServerResponse(message):
            buf.writeInt(Int32(12))
            FfiConverterString.write(message, into: buf)
        case let .Timeout(message):
            buf.writeInt(Int32(13))
            FfiConverterString.write(message, into: buf)

        
        }
    }
}


extension SendfileError: Equatable, Hashable {}

extension SendfileError: Error { }
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    static func read(from buf: Reader) throws -> UInt64 {
        return try lift(buf.readInt())
    }

    static func write(_ value: SwiftType, into buf: Writer) {
        buf.writeInt(lower(value))
    }
}
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    static func read(from buf: Reader) throws -> String {
        let len: Int32 = try buf.readInt()
        return String(bytes: try buf.readBytes(count: Int(len)), encoding: String.Encoding.utf8)!
    }

    static func write(_ value: String, into buf: Writer) {
        let len = Int32(value.utf8.count)
        buf.writeInt(len)
        buf.writeBytes(value.utf8)
    }
}
fileprivate struct FfiConverterDuration: FfiConverterRustBuffer {
    typealias SwiftType = TimeInterval

    static func read(from buf: Reader) throws -> TimeInterval {
        let seconds: UInt64 = try buf.readInt()
        let nanoseconds: UInt32 = try buf.readInt()
        return Double(seconds) + (Double(nanoseconds) / 1.0e9)
    }

    static func write(_ value: TimeInterval, into buf: Writer) {
        if value.rounded(.down) > Double(Int64.max) {
            fatalError("Duration overflow, exceeds max bounds supported by Uniffi")
        }

        if value < 0 {
            fatalError("Invalid duration, must be non-negative")
        }

        let seconds = UInt64(value)
        let nanoseconds = UInt32((value - Double(seconds)) * 1.0e9)
        buf.writeInt(seconds)
        buf.writeInt(nanoseconds)
    }
}
// Helper code for DownloadMeta class is found in ObjectTemplate.swift
// Helper code for DownloaderClient class is found in ObjectTemplate.swift
// Helper code for NativeProvisionedFile class is found in ObjectTemplate.swift
// Helper code for UploaderClient class is found in ObjectTemplate.swift
// Helper code for FileMeta record is found in RecordTemplate.swift
// Helper code for Transport enum is found in EnumTemplate.swift
// Helper code for SendfileError error is found in ErrorTemplate.swift

fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    static func write(_ value: SwiftType, into buf: Writer) {
        guard let value = value else {
            buf.writeInt(Int8(0))
            return
        }
        buf.writeInt(Int8(1))
        FfiConverterString.write(value, into: buf)
    }

    static func read(from buf: Reader) throws -> SwiftType {
        switch try buf.readInt() as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

fileprivate struct FfiConverterOptionDuration: FfiConverterRustBuffer {
    typealias SwiftType = TimeInterval?

    static func write(_ value: SwiftType, into buf: Writer) {
        guard let value = value else {
            buf.writeInt(Int8(0))
            return
        }
        buf.writeInt(Int8(1))
        FfiConverterDuration.write(value, into: buf)
    }

    static func read(from buf: Reader) throws -> SwiftType {
        switch try buf.readInt() as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDuration.read(from: buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}


/**
 * Top level initializers and tear down methods.
 *
 * This is generated by uniffi.
 */
public enum SendfileLibRustLifecycle {
    /**
     * Initialize the FFI and Rust library. This should be only called once per application.
     */
    func initialize() {
        
        // No initialization code needed
        
    }
}