#!/usr/bin/env bash
set -e
set -x

REPO_ROOT=$(git rev-parse --show-toplevel)
cd $REPO_ROOT

rm -fr rust/pkg
wasm-pack build --release --target bundler rust

rm -fr glopfile/dist
rm -fr glopfile/node_modules
(cd glopfile && yarn install && yarn tsc)

rm -fr glopfile-ui/build
rm -fr glopfile-ui/node_modules

# Build for deploy
(cd glopfile-ui && yarn install && yarn build)
# Compress for deploy.
# NOTE: we keep (-k) the original for the weirdos that don't support gzip and
# for our nginx configuration, which will serve up our SPA index whenever
# requesting a URL that doesn't exist on disk.
(cd glopfile-ui/build && find . -type f -name \*.wasm | xargs gzip -k -9)

# Serve for dev
# (cd glopfile-ui && yarn install && yarn start)
