user nginx;

events {
  worker_connections   1000;
}

http {
  # required to proxy websocket
  # based on https://www.nginx.com/blog/websocket-nginx/
  map $http_upgrade $connection_upgrade {
     default Upgrade;
     ''      close;
  }

  upstream relay {
    server relay-1.glopfile.local:8080;
    server relay-2.glopfile.local:8080;
  }

  server {
    listen 8080;
    location / {
      proxy_pass http://relay;

      # long timeout while uploader waits
      # for downloader to connect.
      proxy_read_timeout 10d;

      # required to proxy websocket
      # based on https://www.nginx.com/blog/websocket-nginx/
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header Host $host;
    }
  }
}
