%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.5
%% Version source: file
-module(sendfile_websocket_protocol).

-export([encode_msg/1, encode_msg/2, encode_msg/3]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/2, merge_msgs/3, merge_msgs/4]).
-export([verify_msg/1, verify_msg/2, verify_msg/3]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).
-export([gpb_version_source/0]).

-include("sendfile_websocket_protocol.hrl").
-include_lib("gpb/include/gpb.hrl").

%% enumerated types
-type sendfile_websocket_protocol_session_description_type() :: 'ANSWER' | 'OFFER' | 'PRANSWER' | 'ROLLBACK'.
-export_type([sendfile_websocket_protocol_session_description_type/0]).

%% message types
-type sendfile_websocket_protocol_web_socket_message() :: #sendfile_websocket_protocol_web_socket_message{}.

-type sendfile_websocket_protocol_rtc_signaling_message() :: #sendfile_websocket_protocol_rtc_signaling_message{}.

-type sendfile_websocket_protocol_ice_candidate() :: #sendfile_websocket_protocol_ice_candidate{}.

-type sendfile_websocket_protocol_session_description() :: #sendfile_websocket_protocol_session_description{}.

-type sendfile_websocket_protocol_upload_data_ack() :: #sendfile_websocket_protocol_upload_data_ack{}.

-export_type(['sendfile_websocket_protocol_web_socket_message'/0, 'sendfile_websocket_protocol_rtc_signaling_message'/0, 'sendfile_websocket_protocol_ice_candidate'/0, 'sendfile_websocket_protocol_session_description'/0, 'sendfile_websocket_protocol_upload_data_ack'/0]).
-type '$msg_name'() :: sendfile_websocket_protocol_web_socket_message | sendfile_websocket_protocol_rtc_signaling_message | sendfile_websocket_protocol_ice_candidate | sendfile_websocket_protocol_session_description | sendfile_websocket_protocol_upload_data_ack.
-type '$msg'() :: sendfile_websocket_protocol_web_socket_message() | sendfile_websocket_protocol_rtc_signaling_message() | sendfile_websocket_protocol_ice_candidate() | sendfile_websocket_protocol_session_description() | sendfile_websocket_protocol_upload_data_ack().
-export_type(['$msg_name'/0, '$msg'/0]).

-if(?OTP_RELEASE >= 24).
-dialyzer({no_underspecs, encode_msg/1}).
-endif.
-spec encode_msg('$msg'()) -> binary().
encode_msg(Msg) when tuple_size(Msg) >= 1 -> encode_msg(Msg, element(1, Msg), []).

-if(?OTP_RELEASE >= 24).
-dialyzer({no_underspecs, encode_msg/2}).
-endif.
-spec encode_msg('$msg'(), '$msg_name'() | list()) -> binary().
encode_msg(Msg, MsgName) when is_atom(MsgName) -> encode_msg(Msg, MsgName, []);
encode_msg(Msg, Opts) when tuple_size(Msg) >= 1, is_list(Opts) -> encode_msg(Msg, element(1, Msg), Opts).

-if(?OTP_RELEASE >= 24).
-dialyzer({no_underspecs, encode_msg/3}).
-endif.
-spec encode_msg('$msg'(), '$msg_name'(), list()) -> binary().
encode_msg(Msg, MsgName, Opts) ->
    case proplists:get_bool(verify, Opts) of
        true -> verify_msg(Msg, MsgName, Opts);
        false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        sendfile_websocket_protocol_web_socket_message -> encode_msg_sendfile_websocket_protocol_web_socket_message(id(Msg, TrUserData), TrUserData);
        sendfile_websocket_protocol_rtc_signaling_message -> encode_msg_sendfile_websocket_protocol_rtc_signaling_message(id(Msg, TrUserData), TrUserData);
        sendfile_websocket_protocol_ice_candidate -> encode_msg_sendfile_websocket_protocol_ice_candidate(id(Msg, TrUserData), TrUserData);
        sendfile_websocket_protocol_session_description -> encode_msg_sendfile_websocket_protocol_session_description(id(Msg, TrUserData), TrUserData);
        sendfile_websocket_protocol_upload_data_ack -> encode_msg_sendfile_websocket_protocol_upload_data_ack(id(Msg, TrUserData), TrUserData)
    end.


encode_msg_sendfile_websocket_protocol_web_socket_message(Msg, TrUserData) -> encode_msg_sendfile_websocket_protocol_web_socket_message(Msg, <<>>, TrUserData).


encode_msg_sendfile_websocket_protocol_web_socket_message(#sendfile_websocket_protocol_web_socket_message{inner = F1}, Bin, TrUserData) ->
    if F1 =:= undefined -> Bin;
       true ->
           case id(F1, TrUserData) of
               {rtc_signaling, TF1} -> begin TrTF1 = id(TF1, TrUserData), e_mfield_sendfile_websocket_protocol_web_socket_message_rtc_signaling(TrTF1, <<Bin/binary, 10>>, TrUserData) end;
               {upload_data_ack, TF1} -> begin TrTF1 = id(TF1, TrUserData), e_mfield_sendfile_websocket_protocol_web_socket_message_upload_data_ack(TrTF1, <<Bin/binary, 18>>, TrUserData) end
           end
    end.

encode_msg_sendfile_websocket_protocol_rtc_signaling_message(Msg, TrUserData) -> encode_msg_sendfile_websocket_protocol_rtc_signaling_message(Msg, <<>>, TrUserData).


encode_msg_sendfile_websocket_protocol_rtc_signaling_message(#sendfile_websocket_protocol_rtc_signaling_message{inner = F1}, Bin, TrUserData) ->
    if F1 =:= undefined -> Bin;
       true ->
           case id(F1, TrUserData) of
               {ice_candidate, TF1} -> begin TrTF1 = id(TF1, TrUserData), e_mfield_sendfile_websocket_protocol_rtc_signaling_message_ice_candidate(TrTF1, <<Bin/binary, 10>>, TrUserData) end;
               {session_description, TF1} -> begin TrTF1 = id(TF1, TrUserData), e_mfield_sendfile_websocket_protocol_rtc_signaling_message_session_description(TrTF1, <<Bin/binary, 18>>, TrUserData) end
           end
    end.

encode_msg_sendfile_websocket_protocol_ice_candidate(Msg, TrUserData) -> encode_msg_sendfile_websocket_protocol_ice_candidate(Msg, <<>>, TrUserData).


encode_msg_sendfile_websocket_protocol_ice_candidate(#sendfile_websocket_protocol_ice_candidate{candidate = F1, mid = F2}, Bin, TrUserData) ->
    B1 = if F1 == undefined -> Bin;
            true ->
                begin
                    TrF1 = id(F1, TrUserData),
                    case is_empty_string(TrF1) of
                        true -> Bin;
                        false -> e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
                    end
                end
         end,
    if F2 == undefined -> B1;
       true ->
           begin
               TrF2 = id(F2, TrUserData),
               case is_empty_string(TrF2) of
                   true -> B1;
                   false -> e_type_string(TrF2, <<B1/binary, 18>>, TrUserData)
               end
           end
    end.

encode_msg_sendfile_websocket_protocol_session_description(Msg, TrUserData) -> encode_msg_sendfile_websocket_protocol_session_description(Msg, <<>>, TrUserData).


encode_msg_sendfile_websocket_protocol_session_description(#sendfile_websocket_protocol_session_description{sdp = F1, sdp_type = F2}, Bin, TrUserData) ->
    B1 = if F1 == undefined -> Bin;
            true ->
                begin
                    TrF1 = id(F1, TrUserData),
                    case is_empty_string(TrF1) of
                        true -> Bin;
                        false -> e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
                    end
                end
         end,
    if F2 == undefined -> B1;
       true ->
           begin
               TrF2 = id(F2, TrUserData),
               if TrF2 =:= 'ANSWER'; TrF2 =:= 0 -> B1;
                  true -> 'e_enum_sendfile.websocket.protocol.SessionDescriptionType'(TrF2, <<B1/binary, 16>>, TrUserData)
               end
           end
    end.

encode_msg_sendfile_websocket_protocol_upload_data_ack(Msg, TrUserData) -> encode_msg_sendfile_websocket_protocol_upload_data_ack(Msg, <<>>, TrUserData).


encode_msg_sendfile_websocket_protocol_upload_data_ack(#sendfile_websocket_protocol_upload_data_ack{offset = F1}, Bin, TrUserData) ->
    if F1 == undefined -> Bin;
       true ->
           begin
               TrF1 = id(F1, TrUserData),
               if TrF1 =:= 0 -> Bin;
                  true -> e_varint(TrF1, <<Bin/binary, 8>>, TrUserData)
               end
           end
    end.

e_mfield_sendfile_websocket_protocol_web_socket_message_rtc_signaling(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_sendfile_websocket_protocol_rtc_signaling_message(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_mfield_sendfile_websocket_protocol_web_socket_message_upload_data_ack(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_sendfile_websocket_protocol_upload_data_ack(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_mfield_sendfile_websocket_protocol_rtc_signaling_message_ice_candidate(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_sendfile_websocket_protocol_ice_candidate(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_mfield_sendfile_websocket_protocol_rtc_signaling_message_session_description(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_sendfile_websocket_protocol_session_description(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

'e_enum_sendfile.websocket.protocol.SessionDescriptionType'('ANSWER', Bin, _TrUserData) -> <<Bin/binary, 0>>;
'e_enum_sendfile.websocket.protocol.SessionDescriptionType'('OFFER', Bin, _TrUserData) -> <<Bin/binary, 1>>;
'e_enum_sendfile.websocket.protocol.SessionDescriptionType'('PRANSWER', Bin, _TrUserData) -> <<Bin/binary, 2>>;
'e_enum_sendfile.websocket.protocol.SessionDescriptionType'('ROLLBACK', Bin, _TrUserData) -> <<Bin/binary, 3>>;
'e_enum_sendfile.websocket.protocol.SessionDescriptionType'(V, Bin, _TrUserData) -> e_varint(V, Bin).

-compile({nowarn_unused_function,e_type_sint/3}).
e_type_sint(Value, Bin, _TrUserData) when Value >= 0 -> e_varint(Value * 2, Bin);
e_type_sint(Value, Bin, _TrUserData) -> e_varint(Value * -2 - 1, Bin).

-compile({nowarn_unused_function,e_type_int32/3}).
e_type_int32(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int32(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_int64/3}).
e_type_int64(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int64(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_bool/3}).
e_type_bool(true, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(false, Bin, _TrUserData) -> <<Bin/binary, 0>>;
e_type_bool(1, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(0, Bin, _TrUserData) -> <<Bin/binary, 0>>.

-compile({nowarn_unused_function,e_type_string/3}).
e_type_string(S, Bin, _TrUserData) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

-compile({nowarn_unused_function,e_type_bytes/3}).
e_type_bytes(Bytes, Bin, _TrUserData) when is_binary(Bytes) ->
    Bin2 = e_varint(byte_size(Bytes), Bin),
    <<Bin2/binary, Bytes/binary>>;
e_type_bytes(Bytes, Bin, _TrUserData) when is_list(Bytes) ->
    BytesBin = iolist_to_binary(Bytes),
    Bin2 = e_varint(byte_size(BytesBin), Bin),
    <<Bin2/binary, BytesBin/binary>>.

-compile({nowarn_unused_function,e_type_fixed32/3}).
e_type_fixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little>>.

-compile({nowarn_unused_function,e_type_sfixed32/3}).
e_type_sfixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little-signed>>.

-compile({nowarn_unused_function,e_type_fixed64/3}).
e_type_fixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little>>.

-compile({nowarn_unused_function,e_type_sfixed64/3}).
e_type_sfixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little-signed>>.

-compile({nowarn_unused_function,e_type_float/3}).
e_type_float(V, Bin, _) when is_number(V) -> <<Bin/binary, V:32/little-float>>;
e_type_float(infinity, Bin, _) -> <<Bin/binary, 0:16, 128, 127>>;
e_type_float('-infinity', Bin, _) -> <<Bin/binary, 0:16, 128, 255>>;
e_type_float(nan, Bin, _) -> <<Bin/binary, 0:16, 192, 127>>.

-compile({nowarn_unused_function,e_type_double/3}).
e_type_double(V, Bin, _) when is_number(V) -> <<Bin/binary, V:64/little-float>>;
e_type_double(infinity, Bin, _) -> <<Bin/binary, 0:48, 240, 127>>;
e_type_double('-infinity', Bin, _) -> <<Bin/binary, 0:48, 240, 255>>;
e_type_double(nan, Bin, _) -> <<Bin/binary, 0:48, 248, 127>>.

-compile({nowarn_unused_function,e_unknown_elems/2}).
e_unknown_elems([Elem | Rest], Bin) ->
    BinR = case Elem of
               {varint, FNum, N} ->
                   BinF = e_varint(FNum bsl 3, Bin),
                   e_varint(N, BinF);
               {length_delimited, FNum, Data} ->
                   BinF = e_varint(FNum bsl 3 bor 2, Bin),
                   BinL = e_varint(byte_size(Data), BinF),
                   <<BinL/binary, Data/binary>>;
               {group, FNum, GroupFields} ->
                   Bin1 = e_varint(FNum bsl 3 bor 3, Bin),
                   Bin2 = e_unknown_elems(GroupFields, Bin1),
                   e_varint(FNum bsl 3 bor 4, Bin2);
               {fixed32, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 5, Bin),
                   <<BinF/binary, V:32/little>>;
               {fixed64, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 1, Bin),
                   <<BinF/binary, V:64/little>>
           end,
    e_unknown_elems(Rest, BinR);
e_unknown_elems([], Bin) -> Bin.

-compile({nowarn_unused_function,e_varint/3}).
e_varint(N, Bin, _TrUserData) -> e_varint(N, Bin).

-compile({nowarn_unused_function,e_varint/2}).
e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).

is_empty_string("") -> true;
is_empty_string(<<>>) -> true;
is_empty_string(L) when is_list(L) -> not string_has_chars(L);
is_empty_string(B) when is_binary(B) -> false.

string_has_chars([C | _]) when is_integer(C) -> true;
string_has_chars([H | T]) ->
    case string_has_chars(H) of
        true -> true;
        false -> string_has_chars(T)
    end;
string_has_chars(B) when is_binary(B), byte_size(B) =/= 0 -> true;
string_has_chars(C) when is_integer(C) -> true;
string_has_chars(<<>>) -> false;
string_has_chars([]) -> false.


decode_msg(Bin, MsgName) when is_binary(Bin) -> decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) ->
    TrUserData = proplists:get_value(user_data, Opts),
    decode_msg_1_catch(Bin, MsgName, TrUserData).

-ifdef('OTP_RELEASE').
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason:StackTrace ->
            erlang:raise(error, Reason, StackTrace);
        Class:Reason:StackTrace -> error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-else.
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason ->
            erlang:raise(error, Reason,
                         erlang:get_stacktrace());
        Class:Reason ->
            StackTrace = erlang:get_stacktrace(),
            error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-endif.

decode_msg_2_doit(sendfile_websocket_protocol_web_socket_message, Bin, TrUserData) -> id(decode_msg_sendfile_websocket_protocol_web_socket_message(Bin, TrUserData), TrUserData);
decode_msg_2_doit(sendfile_websocket_protocol_rtc_signaling_message, Bin, TrUserData) -> id(decode_msg_sendfile_websocket_protocol_rtc_signaling_message(Bin, TrUserData), TrUserData);
decode_msg_2_doit(sendfile_websocket_protocol_ice_candidate, Bin, TrUserData) -> id(decode_msg_sendfile_websocket_protocol_ice_candidate(Bin, TrUserData), TrUserData);
decode_msg_2_doit(sendfile_websocket_protocol_session_description, Bin, TrUserData) -> id(decode_msg_sendfile_websocket_protocol_session_description(Bin, TrUserData), TrUserData);
decode_msg_2_doit(sendfile_websocket_protocol_upload_data_ack, Bin, TrUserData) -> id(decode_msg_sendfile_websocket_protocol_upload_data_ack(Bin, TrUserData), TrUserData).



decode_msg_sendfile_websocket_protocol_web_socket_message(Bin, TrUserData) -> dfp_read_field_def_sendfile_websocket_protocol_web_socket_message(Bin, 0, 0, 0, id(undefined, TrUserData), TrUserData).

dfp_read_field_def_sendfile_websocket_protocol_web_socket_message(<<10, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_sendfile_websocket_protocol_web_socket_message_rtc_signaling(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_sendfile_websocket_protocol_web_socket_message(<<18, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_sendfile_websocket_protocol_web_socket_message_upload_data_ack(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_sendfile_websocket_protocol_web_socket_message(<<>>, 0, 0, _, F@_1, _) -> #sendfile_websocket_protocol_web_socket_message{inner = F@_1};
dfp_read_field_def_sendfile_websocket_protocol_web_socket_message(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_sendfile_websocket_protocol_web_socket_message(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_sendfile_websocket_protocol_web_socket_message(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 ->
    dg_read_field_def_sendfile_websocket_protocol_web_socket_message(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_sendfile_websocket_protocol_web_socket_message(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_sendfile_websocket_protocol_web_socket_message_rtc_signaling(Rest, 0, 0, 0, F@_1, TrUserData);
        18 -> d_field_sendfile_websocket_protocol_web_socket_message_upload_data_ack(Rest, 0, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_sendfile_websocket_protocol_web_socket_message(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                1 -> skip_64_sendfile_websocket_protocol_web_socket_message(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                2 -> skip_length_delimited_sendfile_websocket_protocol_web_socket_message(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                3 -> skip_group_sendfile_websocket_protocol_web_socket_message(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                5 -> skip_32_sendfile_websocket_protocol_web_socket_message(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
            end
    end;
dg_read_field_def_sendfile_websocket_protocol_web_socket_message(<<>>, 0, 0, _, F@_1, _) -> #sendfile_websocket_protocol_web_socket_message{inner = F@_1}.

d_field_sendfile_websocket_protocol_web_socket_message_rtc_signaling(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 ->
    d_field_sendfile_websocket_protocol_web_socket_message_rtc_signaling(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_sendfile_websocket_protocol_web_socket_message_rtc_signaling(<<0:1, X:7, Rest/binary>>, N, Acc, F, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_sendfile_websocket_protocol_rtc_signaling_message(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_sendfile_websocket_protocol_web_socket_message(RestF,
                                                                      0,
                                                                      0,
                                                                      F,
                                                                      case Prev of
                                                                          undefined -> id({rtc_signaling, NewFValue}, TrUserData);
                                                                          {rtc_signaling, MVPrev} -> id({rtc_signaling, merge_msg_sendfile_websocket_protocol_rtc_signaling_message(MVPrev, NewFValue, TrUserData)}, TrUserData);
                                                                          _ -> id({rtc_signaling, NewFValue}, TrUserData)
                                                                      end,
                                                                      TrUserData).

d_field_sendfile_websocket_protocol_web_socket_message_upload_data_ack(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 ->
    d_field_sendfile_websocket_protocol_web_socket_message_upload_data_ack(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_sendfile_websocket_protocol_web_socket_message_upload_data_ack(<<0:1, X:7, Rest/binary>>, N, Acc, F, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_sendfile_websocket_protocol_upload_data_ack(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_sendfile_websocket_protocol_web_socket_message(RestF,
                                                                      0,
                                                                      0,
                                                                      F,
                                                                      case Prev of
                                                                          undefined -> id({upload_data_ack, NewFValue}, TrUserData);
                                                                          {upload_data_ack, MVPrev} -> id({upload_data_ack, merge_msg_sendfile_websocket_protocol_upload_data_ack(MVPrev, NewFValue, TrUserData)}, TrUserData);
                                                                          _ -> id({upload_data_ack, NewFValue}, TrUserData)
                                                                      end,
                                                                      TrUserData).

skip_varint_sendfile_websocket_protocol_web_socket_message(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_sendfile_websocket_protocol_web_socket_message(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_sendfile_websocket_protocol_web_socket_message(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_sendfile_websocket_protocol_web_socket_message(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_sendfile_websocket_protocol_web_socket_message(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 ->
    skip_length_delimited_sendfile_websocket_protocol_web_socket_message(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_sendfile_websocket_protocol_web_socket_message(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_sendfile_websocket_protocol_web_socket_message(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_sendfile_websocket_protocol_web_socket_message(Bin, _, Z2, FNum, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_sendfile_websocket_protocol_web_socket_message(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_sendfile_websocket_protocol_web_socket_message(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_sendfile_websocket_protocol_web_socket_message(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_sendfile_websocket_protocol_web_socket_message(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_sendfile_websocket_protocol_web_socket_message(Rest, Z1, Z2, F, F@_1, TrUserData).

decode_msg_sendfile_websocket_protocol_rtc_signaling_message(Bin, TrUserData) -> dfp_read_field_def_sendfile_websocket_protocol_rtc_signaling_message(Bin, 0, 0, 0, id(undefined, TrUserData), TrUserData).

dfp_read_field_def_sendfile_websocket_protocol_rtc_signaling_message(<<10, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_sendfile_websocket_protocol_rtc_signaling_message_ice_candidate(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_sendfile_websocket_protocol_rtc_signaling_message(<<18, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_sendfile_websocket_protocol_rtc_signaling_message_session_description(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_sendfile_websocket_protocol_rtc_signaling_message(<<>>, 0, 0, _, F@_1, _) -> #sendfile_websocket_protocol_rtc_signaling_message{inner = F@_1};
dfp_read_field_def_sendfile_websocket_protocol_rtc_signaling_message(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_sendfile_websocket_protocol_rtc_signaling_message(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_sendfile_websocket_protocol_rtc_signaling_message(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 ->
    dg_read_field_def_sendfile_websocket_protocol_rtc_signaling_message(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_sendfile_websocket_protocol_rtc_signaling_message(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_sendfile_websocket_protocol_rtc_signaling_message_ice_candidate(Rest, 0, 0, 0, F@_1, TrUserData);
        18 -> d_field_sendfile_websocket_protocol_rtc_signaling_message_session_description(Rest, 0, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_sendfile_websocket_protocol_rtc_signaling_message(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                1 -> skip_64_sendfile_websocket_protocol_rtc_signaling_message(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                2 -> skip_length_delimited_sendfile_websocket_protocol_rtc_signaling_message(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                3 -> skip_group_sendfile_websocket_protocol_rtc_signaling_message(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                5 -> skip_32_sendfile_websocket_protocol_rtc_signaling_message(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
            end
    end;
dg_read_field_def_sendfile_websocket_protocol_rtc_signaling_message(<<>>, 0, 0, _, F@_1, _) -> #sendfile_websocket_protocol_rtc_signaling_message{inner = F@_1}.

d_field_sendfile_websocket_protocol_rtc_signaling_message_ice_candidate(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 ->
    d_field_sendfile_websocket_protocol_rtc_signaling_message_ice_candidate(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_sendfile_websocket_protocol_rtc_signaling_message_ice_candidate(<<0:1, X:7, Rest/binary>>, N, Acc, F, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_sendfile_websocket_protocol_ice_candidate(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_sendfile_websocket_protocol_rtc_signaling_message(RestF,
                                                                         0,
                                                                         0,
                                                                         F,
                                                                         case Prev of
                                                                             undefined -> id({ice_candidate, NewFValue}, TrUserData);
                                                                             {ice_candidate, MVPrev} -> id({ice_candidate, merge_msg_sendfile_websocket_protocol_ice_candidate(MVPrev, NewFValue, TrUserData)}, TrUserData);
                                                                             _ -> id({ice_candidate, NewFValue}, TrUserData)
                                                                         end,
                                                                         TrUserData).

d_field_sendfile_websocket_protocol_rtc_signaling_message_session_description(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 ->
    d_field_sendfile_websocket_protocol_rtc_signaling_message_session_description(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_sendfile_websocket_protocol_rtc_signaling_message_session_description(<<0:1, X:7, Rest/binary>>, N, Acc, F, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_sendfile_websocket_protocol_session_description(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_sendfile_websocket_protocol_rtc_signaling_message(RestF,
                                                                         0,
                                                                         0,
                                                                         F,
                                                                         case Prev of
                                                                             undefined -> id({session_description, NewFValue}, TrUserData);
                                                                             {session_description, MVPrev} -> id({session_description, merge_msg_sendfile_websocket_protocol_session_description(MVPrev, NewFValue, TrUserData)}, TrUserData);
                                                                             _ -> id({session_description, NewFValue}, TrUserData)
                                                                         end,
                                                                         TrUserData).

skip_varint_sendfile_websocket_protocol_rtc_signaling_message(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_sendfile_websocket_protocol_rtc_signaling_message(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_sendfile_websocket_protocol_rtc_signaling_message(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_sendfile_websocket_protocol_rtc_signaling_message(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_sendfile_websocket_protocol_rtc_signaling_message(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 ->
    skip_length_delimited_sendfile_websocket_protocol_rtc_signaling_message(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_sendfile_websocket_protocol_rtc_signaling_message(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_sendfile_websocket_protocol_rtc_signaling_message(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_sendfile_websocket_protocol_rtc_signaling_message(Bin, _, Z2, FNum, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_sendfile_websocket_protocol_rtc_signaling_message(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_sendfile_websocket_protocol_rtc_signaling_message(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_sendfile_websocket_protocol_rtc_signaling_message(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_sendfile_websocket_protocol_rtc_signaling_message(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_sendfile_websocket_protocol_rtc_signaling_message(Rest, Z1, Z2, F, F@_1, TrUserData).

decode_msg_sendfile_websocket_protocol_ice_candidate(Bin, TrUserData) -> dfp_read_field_def_sendfile_websocket_protocol_ice_candidate(Bin, 0, 0, 0, id(<<>>, TrUserData), id(<<>>, TrUserData), TrUserData).

dfp_read_field_def_sendfile_websocket_protocol_ice_candidate(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_sendfile_websocket_protocol_ice_candidate_candidate(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_sendfile_websocket_protocol_ice_candidate(<<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_sendfile_websocket_protocol_ice_candidate_mid(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_sendfile_websocket_protocol_ice_candidate(<<>>, 0, 0, _, F@_1, F@_2, _) -> #sendfile_websocket_protocol_ice_candidate{candidate = F@_1, mid = F@_2};
dfp_read_field_def_sendfile_websocket_protocol_ice_candidate(Other, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dg_read_field_def_sendfile_websocket_protocol_ice_candidate(Other, Z1, Z2, F, F@_1, F@_2, TrUserData).

dg_read_field_def_sendfile_websocket_protocol_ice_candidate(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 32 - 7 ->
    dg_read_field_def_sendfile_websocket_protocol_ice_candidate(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
dg_read_field_def_sendfile_websocket_protocol_ice_candidate(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_sendfile_websocket_protocol_ice_candidate_candidate(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        18 -> d_field_sendfile_websocket_protocol_ice_candidate_mid(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_sendfile_websocket_protocol_ice_candidate(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                1 -> skip_64_sendfile_websocket_protocol_ice_candidate(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                2 -> skip_length_delimited_sendfile_websocket_protocol_ice_candidate(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                3 -> skip_group_sendfile_websocket_protocol_ice_candidate(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                5 -> skip_32_sendfile_websocket_protocol_ice_candidate(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData)
            end
    end;
dg_read_field_def_sendfile_websocket_protocol_ice_candidate(<<>>, 0, 0, _, F@_1, F@_2, _) -> #sendfile_websocket_protocol_ice_candidate{candidate = F@_1, mid = F@_2}.

d_field_sendfile_websocket_protocol_ice_candidate_candidate(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 ->
    d_field_sendfile_websocket_protocol_ice_candidate_candidate(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_sendfile_websocket_protocol_ice_candidate_candidate(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_sendfile_websocket_protocol_ice_candidate(RestF, 0, 0, F, NewFValue, F@_2, TrUserData).

d_field_sendfile_websocket_protocol_ice_candidate_mid(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> d_field_sendfile_websocket_protocol_ice_candidate_mid(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_sendfile_websocket_protocol_ice_candidate_mid(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_sendfile_websocket_protocol_ice_candidate(RestF, 0, 0, F, F@_1, NewFValue, TrUserData).

skip_varint_sendfile_websocket_protocol_ice_candidate(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> skip_varint_sendfile_websocket_protocol_ice_candidate(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
skip_varint_sendfile_websocket_protocol_ice_candidate(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_sendfile_websocket_protocol_ice_candidate(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_length_delimited_sendfile_websocket_protocol_ice_candidate(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 ->
    skip_length_delimited_sendfile_websocket_protocol_ice_candidate(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
skip_length_delimited_sendfile_websocket_protocol_ice_candidate(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_sendfile_websocket_protocol_ice_candidate(Rest2, 0, 0, F, F@_1, F@_2, TrUserData).

skip_group_sendfile_websocket_protocol_ice_candidate(Bin, _, Z2, FNum, F@_1, F@_2, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_sendfile_websocket_protocol_ice_candidate(Rest, 0, Z2, FNum, F@_1, F@_2, TrUserData).

skip_32_sendfile_websocket_protocol_ice_candidate(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_sendfile_websocket_protocol_ice_candidate(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_64_sendfile_websocket_protocol_ice_candidate(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_sendfile_websocket_protocol_ice_candidate(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

decode_msg_sendfile_websocket_protocol_session_description(Bin, TrUserData) -> dfp_read_field_def_sendfile_websocket_protocol_session_description(Bin, 0, 0, 0, id(<<>>, TrUserData), id('ANSWER', TrUserData), TrUserData).

dfp_read_field_def_sendfile_websocket_protocol_session_description(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_sendfile_websocket_protocol_session_description_sdp(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_sendfile_websocket_protocol_session_description(<<16, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_sendfile_websocket_protocol_session_description_sdp_type(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_sendfile_websocket_protocol_session_description(<<>>, 0, 0, _, F@_1, F@_2, _) -> #sendfile_websocket_protocol_session_description{sdp = F@_1, sdp_type = F@_2};
dfp_read_field_def_sendfile_websocket_protocol_session_description(Other, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dg_read_field_def_sendfile_websocket_protocol_session_description(Other, Z1, Z2, F, F@_1, F@_2, TrUserData).

dg_read_field_def_sendfile_websocket_protocol_session_description(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 32 - 7 ->
    dg_read_field_def_sendfile_websocket_protocol_session_description(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
dg_read_field_def_sendfile_websocket_protocol_session_description(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_sendfile_websocket_protocol_session_description_sdp(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        16 -> d_field_sendfile_websocket_protocol_session_description_sdp_type(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_sendfile_websocket_protocol_session_description(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                1 -> skip_64_sendfile_websocket_protocol_session_description(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                2 -> skip_length_delimited_sendfile_websocket_protocol_session_description(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                3 -> skip_group_sendfile_websocket_protocol_session_description(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                5 -> skip_32_sendfile_websocket_protocol_session_description(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData)
            end
    end;
dg_read_field_def_sendfile_websocket_protocol_session_description(<<>>, 0, 0, _, F@_1, F@_2, _) -> #sendfile_websocket_protocol_session_description{sdp = F@_1, sdp_type = F@_2}.

d_field_sendfile_websocket_protocol_session_description_sdp(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 ->
    d_field_sendfile_websocket_protocol_session_description_sdp(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_sendfile_websocket_protocol_session_description_sdp(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_sendfile_websocket_protocol_session_description(RestF, 0, 0, F, NewFValue, F@_2, TrUserData).

d_field_sendfile_websocket_protocol_session_description_sdp_type(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 ->
    d_field_sendfile_websocket_protocol_session_description_sdp_type(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_sendfile_websocket_protocol_session_description_sdp_type(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, TrUserData) ->
    {NewFValue, RestF} = {id('d_enum_sendfile.websocket.protocol.SessionDescriptionType'(begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end), TrUserData), Rest},
    dfp_read_field_def_sendfile_websocket_protocol_session_description(RestF, 0, 0, F, F@_1, NewFValue, TrUserData).

skip_varint_sendfile_websocket_protocol_session_description(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> skip_varint_sendfile_websocket_protocol_session_description(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
skip_varint_sendfile_websocket_protocol_session_description(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_sendfile_websocket_protocol_session_description(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_length_delimited_sendfile_websocket_protocol_session_description(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 ->
    skip_length_delimited_sendfile_websocket_protocol_session_description(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
skip_length_delimited_sendfile_websocket_protocol_session_description(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_sendfile_websocket_protocol_session_description(Rest2, 0, 0, F, F@_1, F@_2, TrUserData).

skip_group_sendfile_websocket_protocol_session_description(Bin, _, Z2, FNum, F@_1, F@_2, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_sendfile_websocket_protocol_session_description(Rest, 0, Z2, FNum, F@_1, F@_2, TrUserData).

skip_32_sendfile_websocket_protocol_session_description(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_sendfile_websocket_protocol_session_description(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_64_sendfile_websocket_protocol_session_description(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_sendfile_websocket_protocol_session_description(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

decode_msg_sendfile_websocket_protocol_upload_data_ack(Bin, TrUserData) -> dfp_read_field_def_sendfile_websocket_protocol_upload_data_ack(Bin, 0, 0, 0, id(0, TrUserData), TrUserData).

dfp_read_field_def_sendfile_websocket_protocol_upload_data_ack(<<8, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_sendfile_websocket_protocol_upload_data_ack_offset(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_sendfile_websocket_protocol_upload_data_ack(<<>>, 0, 0, _, F@_1, _) -> #sendfile_websocket_protocol_upload_data_ack{offset = F@_1};
dfp_read_field_def_sendfile_websocket_protocol_upload_data_ack(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_sendfile_websocket_protocol_upload_data_ack(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_sendfile_websocket_protocol_upload_data_ack(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_sendfile_websocket_protocol_upload_data_ack(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_sendfile_websocket_protocol_upload_data_ack(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        8 -> d_field_sendfile_websocket_protocol_upload_data_ack_offset(Rest, 0, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_sendfile_websocket_protocol_upload_data_ack(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                1 -> skip_64_sendfile_websocket_protocol_upload_data_ack(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                2 -> skip_length_delimited_sendfile_websocket_protocol_upload_data_ack(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                3 -> skip_group_sendfile_websocket_protocol_upload_data_ack(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                5 -> skip_32_sendfile_websocket_protocol_upload_data_ack(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
            end
    end;
dg_read_field_def_sendfile_websocket_protocol_upload_data_ack(<<>>, 0, 0, _, F@_1, _) -> #sendfile_websocket_protocol_upload_data_ack{offset = F@_1}.

d_field_sendfile_websocket_protocol_upload_data_ack_offset(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_sendfile_websocket_protocol_upload_data_ack_offset(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_sendfile_websocket_protocol_upload_data_ack_offset(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 18446744073709551615, TrUserData), Rest},
    dfp_read_field_def_sendfile_websocket_protocol_upload_data_ack(RestF, 0, 0, F, NewFValue, TrUserData).

skip_varint_sendfile_websocket_protocol_upload_data_ack(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_sendfile_websocket_protocol_upload_data_ack(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_sendfile_websocket_protocol_upload_data_ack(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_sendfile_websocket_protocol_upload_data_ack(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_sendfile_websocket_protocol_upload_data_ack(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 ->
    skip_length_delimited_sendfile_websocket_protocol_upload_data_ack(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_sendfile_websocket_protocol_upload_data_ack(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_sendfile_websocket_protocol_upload_data_ack(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_sendfile_websocket_protocol_upload_data_ack(Bin, _, Z2, FNum, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_sendfile_websocket_protocol_upload_data_ack(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_sendfile_websocket_protocol_upload_data_ack(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_sendfile_websocket_protocol_upload_data_ack(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_sendfile_websocket_protocol_upload_data_ack(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_sendfile_websocket_protocol_upload_data_ack(Rest, Z1, Z2, F, F@_1, TrUserData).

'd_enum_sendfile.websocket.protocol.SessionDescriptionType'(0) -> 'ANSWER';
'd_enum_sendfile.websocket.protocol.SessionDescriptionType'(1) -> 'OFFER';
'd_enum_sendfile.websocket.protocol.SessionDescriptionType'(2) -> 'PRANSWER';
'd_enum_sendfile.websocket.protocol.SessionDescriptionType'(3) -> 'ROLLBACK';
'd_enum_sendfile.websocket.protocol.SessionDescriptionType'(V) -> V.

read_group(Bin, FieldNum) ->
    {NumBytes, EndTagLen} = read_gr_b(Bin, 0, 0, 0, 0, FieldNum),
    <<Group:NumBytes/binary, _:EndTagLen/binary, Rest/binary>> = Bin,
    {Group, Rest}.

%% Like skipping over fields, but record the total length,
%% Each field is <(FieldNum bsl 3) bor FieldType> ++ <FieldValue>
%% Record the length because varints may be non-optimally encoded.
%%
%% Groups can be nested, but assume the same FieldNum cannot be nested
%% because group field numbers are shared with the rest of the fields
%% numbers. Thus we can search just for an group-end with the same
%% field number.
%%
%% (The only time the same group field number could occur would
%% be in a nested sub message, but then it would be inside a
%% length-delimited entry, which we skip-read by length.)
read_gr_b(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen, FieldNum)
  when N < (32-7) ->
    read_gr_b(Tl, N+7, X bsl N + Acc, NumBytes, TagLen+1, FieldNum);
read_gr_b(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen,
          FieldNum) ->
    Key = X bsl N + Acc,
    TagLen1 = TagLen + 1,
    case {Key bsr 3, Key band 7} of
        {FieldNum, 4} -> % 4 = group_end
            {NumBytes, TagLen1};
        {_, 0} -> % 0 = varint
            read_gr_vi(Tl, 0, NumBytes + TagLen1, FieldNum);
        {_, 1} -> % 1 = bits64
            <<_:64, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 8, 0, FieldNum);
        {_, 2} -> % 2 = length_delimited
            read_gr_ld(Tl, 0, 0, NumBytes + TagLen1, FieldNum);
        {_, 3} -> % 3 = group_start
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 4} -> % 4 = group_end
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 5} -> % 5 = bits32
            <<_:32, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 4, 0, FieldNum)
    end.

read_gr_vi(<<1:1, _:7, Tl/binary>>, N, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_vi(Tl, N+7, NumBytes+1, FieldNum);
read_gr_vi(<<0:1, _:7, Tl/binary>>, _, NumBytes, FieldNum) ->
    read_gr_b(Tl, 0, 0, NumBytes+1, 0, FieldNum).

read_gr_ld(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_ld(Tl, N+7, X bsl N + Acc, NumBytes+1, FieldNum);
read_gr_ld(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) ->
    Len = X bsl N + Acc,
    NumBytes1 = NumBytes + 1,
    <<_:Len/binary, Tl2/binary>> = Tl,
    read_gr_b(Tl2, 0, 0, NumBytes1 + Len, 0, FieldNum).

merge_msgs(Prev, New) when element(1, Prev) =:= element(1, New) -> merge_msgs(Prev, New, element(1, Prev), []).

merge_msgs(Prev, New, MsgName) when is_atom(MsgName) -> merge_msgs(Prev, New, MsgName, []);
merge_msgs(Prev, New, Opts) when element(1, Prev) =:= element(1, New), is_list(Opts) -> merge_msgs(Prev, New, element(1, Prev), Opts).

merge_msgs(Prev, New, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        sendfile_websocket_protocol_web_socket_message -> merge_msg_sendfile_websocket_protocol_web_socket_message(Prev, New, TrUserData);
        sendfile_websocket_protocol_rtc_signaling_message -> merge_msg_sendfile_websocket_protocol_rtc_signaling_message(Prev, New, TrUserData);
        sendfile_websocket_protocol_ice_candidate -> merge_msg_sendfile_websocket_protocol_ice_candidate(Prev, New, TrUserData);
        sendfile_websocket_protocol_session_description -> merge_msg_sendfile_websocket_protocol_session_description(Prev, New, TrUserData);
        sendfile_websocket_protocol_upload_data_ack -> merge_msg_sendfile_websocket_protocol_upload_data_ack(Prev, New, TrUserData)
    end.

-compile({nowarn_unused_function,merge_msg_sendfile_websocket_protocol_web_socket_message/3}).
merge_msg_sendfile_websocket_protocol_web_socket_message(#sendfile_websocket_protocol_web_socket_message{inner = PFinner}, #sendfile_websocket_protocol_web_socket_message{inner = NFinner}, TrUserData) ->
    #sendfile_websocket_protocol_web_socket_message{inner =
                                                        case {PFinner, NFinner} of
                                                            {{rtc_signaling, OPFinner}, {rtc_signaling, ONFinner}} -> {rtc_signaling, merge_msg_sendfile_websocket_protocol_rtc_signaling_message(OPFinner, ONFinner, TrUserData)};
                                                            {{upload_data_ack, OPFinner}, {upload_data_ack, ONFinner}} -> {upload_data_ack, merge_msg_sendfile_websocket_protocol_upload_data_ack(OPFinner, ONFinner, TrUserData)};
                                                            {_, undefined} -> PFinner;
                                                            _ -> NFinner
                                                        end}.

-compile({nowarn_unused_function,merge_msg_sendfile_websocket_protocol_rtc_signaling_message/3}).
merge_msg_sendfile_websocket_protocol_rtc_signaling_message(#sendfile_websocket_protocol_rtc_signaling_message{inner = PFinner}, #sendfile_websocket_protocol_rtc_signaling_message{inner = NFinner}, TrUserData) ->
    #sendfile_websocket_protocol_rtc_signaling_message{inner =
                                                           case {PFinner, NFinner} of
                                                               {{ice_candidate, OPFinner}, {ice_candidate, ONFinner}} -> {ice_candidate, merge_msg_sendfile_websocket_protocol_ice_candidate(OPFinner, ONFinner, TrUserData)};
                                                               {{session_description, OPFinner}, {session_description, ONFinner}} -> {session_description, merge_msg_sendfile_websocket_protocol_session_description(OPFinner, ONFinner, TrUserData)};
                                                               {_, undefined} -> PFinner;
                                                               _ -> NFinner
                                                           end}.

-compile({nowarn_unused_function,merge_msg_sendfile_websocket_protocol_ice_candidate/3}).
merge_msg_sendfile_websocket_protocol_ice_candidate(#sendfile_websocket_protocol_ice_candidate{candidate = PFcandidate, mid = PFmid}, #sendfile_websocket_protocol_ice_candidate{candidate = NFcandidate, mid = NFmid}, _) ->
    #sendfile_websocket_protocol_ice_candidate{candidate =
                                                   if NFcandidate =:= undefined -> PFcandidate;
                                                      true -> NFcandidate
                                                   end,
                                               mid =
                                                   if NFmid =:= undefined -> PFmid;
                                                      true -> NFmid
                                                   end}.

-compile({nowarn_unused_function,merge_msg_sendfile_websocket_protocol_session_description/3}).
merge_msg_sendfile_websocket_protocol_session_description(#sendfile_websocket_protocol_session_description{sdp = PFsdp, sdp_type = PFsdp_type}, #sendfile_websocket_protocol_session_description{sdp = NFsdp, sdp_type = NFsdp_type}, _) ->
    #sendfile_websocket_protocol_session_description{sdp =
                                                         if NFsdp =:= undefined -> PFsdp;
                                                            true -> NFsdp
                                                         end,
                                                     sdp_type =
                                                         if NFsdp_type =:= undefined -> PFsdp_type;
                                                            true -> NFsdp_type
                                                         end}.

-compile({nowarn_unused_function,merge_msg_sendfile_websocket_protocol_upload_data_ack/3}).
merge_msg_sendfile_websocket_protocol_upload_data_ack(#sendfile_websocket_protocol_upload_data_ack{offset = PFoffset}, #sendfile_websocket_protocol_upload_data_ack{offset = NFoffset}, _) ->
    #sendfile_websocket_protocol_upload_data_ack{offset =
                                                     if NFoffset =:= undefined -> PFoffset;
                                                        true -> NFoffset
                                                     end}.


verify_msg(Msg) when tuple_size(Msg) >= 1 -> verify_msg(Msg, element(1, Msg), []);
verify_msg(X) -> mk_type_error(not_a_known_message, X, []).

verify_msg(Msg, MsgName) when is_atom(MsgName) -> verify_msg(Msg, MsgName, []);
verify_msg(Msg, Opts) when tuple_size(Msg) >= 1 -> verify_msg(Msg, element(1, Msg), Opts);
verify_msg(X, _Opts) -> mk_type_error(not_a_known_message, X, []).

verify_msg(Msg, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        sendfile_websocket_protocol_web_socket_message -> v_msg_sendfile_websocket_protocol_web_socket_message(Msg, [MsgName], TrUserData);
        sendfile_websocket_protocol_rtc_signaling_message -> v_msg_sendfile_websocket_protocol_rtc_signaling_message(Msg, [MsgName], TrUserData);
        sendfile_websocket_protocol_ice_candidate -> v_msg_sendfile_websocket_protocol_ice_candidate(Msg, [MsgName], TrUserData);
        sendfile_websocket_protocol_session_description -> v_msg_sendfile_websocket_protocol_session_description(Msg, [MsgName], TrUserData);
        sendfile_websocket_protocol_upload_data_ack -> v_msg_sendfile_websocket_protocol_upload_data_ack(Msg, [MsgName], TrUserData);
        _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-compile({nowarn_unused_function,v_msg_sendfile_websocket_protocol_web_socket_message/3}).
-dialyzer({nowarn_function,v_msg_sendfile_websocket_protocol_web_socket_message/3}).
v_msg_sendfile_websocket_protocol_web_socket_message(#sendfile_websocket_protocol_web_socket_message{inner = F1}, Path, TrUserData) ->
    case F1 of
        undefined -> ok;
        {rtc_signaling, OF1} -> v_msg_sendfile_websocket_protocol_rtc_signaling_message(OF1, [rtc_signaling, inner | Path], TrUserData);
        {upload_data_ack, OF1} -> v_msg_sendfile_websocket_protocol_upload_data_ack(OF1, [upload_data_ack, inner | Path], TrUserData);
        _ -> mk_type_error(invalid_oneof, F1, [inner | Path])
    end,
    ok;
v_msg_sendfile_websocket_protocol_web_socket_message(X, Path, _TrUserData) -> mk_type_error({expected_msg, sendfile_websocket_protocol_web_socket_message}, X, Path).

-compile({nowarn_unused_function,v_msg_sendfile_websocket_protocol_rtc_signaling_message/3}).
-dialyzer({nowarn_function,v_msg_sendfile_websocket_protocol_rtc_signaling_message/3}).
v_msg_sendfile_websocket_protocol_rtc_signaling_message(#sendfile_websocket_protocol_rtc_signaling_message{inner = F1}, Path, TrUserData) ->
    case F1 of
        undefined -> ok;
        {ice_candidate, OF1} -> v_msg_sendfile_websocket_protocol_ice_candidate(OF1, [ice_candidate, inner | Path], TrUserData);
        {session_description, OF1} -> v_msg_sendfile_websocket_protocol_session_description(OF1, [session_description, inner | Path], TrUserData);
        _ -> mk_type_error(invalid_oneof, F1, [inner | Path])
    end,
    ok;
v_msg_sendfile_websocket_protocol_rtc_signaling_message(X, Path, _TrUserData) -> mk_type_error({expected_msg, sendfile_websocket_protocol_rtc_signaling_message}, X, Path).

-compile({nowarn_unused_function,v_msg_sendfile_websocket_protocol_ice_candidate/3}).
-dialyzer({nowarn_function,v_msg_sendfile_websocket_protocol_ice_candidate/3}).
v_msg_sendfile_websocket_protocol_ice_candidate(#sendfile_websocket_protocol_ice_candidate{candidate = F1, mid = F2}, Path, TrUserData) ->
    if F1 == undefined -> ok;
       true -> v_type_string(F1, [candidate | Path], TrUserData)
    end,
    if F2 == undefined -> ok;
       true -> v_type_string(F2, [mid | Path], TrUserData)
    end,
    ok;
v_msg_sendfile_websocket_protocol_ice_candidate(X, Path, _TrUserData) -> mk_type_error({expected_msg, sendfile_websocket_protocol_ice_candidate}, X, Path).

-compile({nowarn_unused_function,v_msg_sendfile_websocket_protocol_session_description/3}).
-dialyzer({nowarn_function,v_msg_sendfile_websocket_protocol_session_description/3}).
v_msg_sendfile_websocket_protocol_session_description(#sendfile_websocket_protocol_session_description{sdp = F1, sdp_type = F2}, Path, TrUserData) ->
    if F1 == undefined -> ok;
       true -> v_type_string(F1, [sdp | Path], TrUserData)
    end,
    if F2 == undefined -> ok;
       true -> 'v_enum_sendfile.websocket.protocol.SessionDescriptionType'(F2, [sdp_type | Path], TrUserData)
    end,
    ok;
v_msg_sendfile_websocket_protocol_session_description(X, Path, _TrUserData) -> mk_type_error({expected_msg, sendfile_websocket_protocol_session_description}, X, Path).

-compile({nowarn_unused_function,v_msg_sendfile_websocket_protocol_upload_data_ack/3}).
-dialyzer({nowarn_function,v_msg_sendfile_websocket_protocol_upload_data_ack/3}).
v_msg_sendfile_websocket_protocol_upload_data_ack(#sendfile_websocket_protocol_upload_data_ack{offset = F1}, Path, TrUserData) ->
    if F1 == undefined -> ok;
       true -> v_type_uint64(F1, [offset | Path], TrUserData)
    end,
    ok;
v_msg_sendfile_websocket_protocol_upload_data_ack(X, Path, _TrUserData) -> mk_type_error({expected_msg, sendfile_websocket_protocol_upload_data_ack}, X, Path).

-compile({nowarn_unused_function,'v_enum_sendfile.websocket.protocol.SessionDescriptionType'/3}).
-dialyzer({nowarn_function,'v_enum_sendfile.websocket.protocol.SessionDescriptionType'/3}).
'v_enum_sendfile.websocket.protocol.SessionDescriptionType'('ANSWER', _Path, _TrUserData) -> ok;
'v_enum_sendfile.websocket.protocol.SessionDescriptionType'('OFFER', _Path, _TrUserData) -> ok;
'v_enum_sendfile.websocket.protocol.SessionDescriptionType'('PRANSWER', _Path, _TrUserData) -> ok;
'v_enum_sendfile.websocket.protocol.SessionDescriptionType'('ROLLBACK', _Path, _TrUserData) -> ok;
'v_enum_sendfile.websocket.protocol.SessionDescriptionType'(V, _Path, _TrUserData) when -2147483648 =< V, V =< 2147483647, is_integer(V) -> ok;
'v_enum_sendfile.websocket.protocol.SessionDescriptionType'(X, Path, _TrUserData) -> mk_type_error({invalid_enum, 'sendfile.websocket.protocol.SessionDescriptionType'}, X, Path).

-compile({nowarn_unused_function,v_type_uint64/3}).
-dialyzer({nowarn_function,v_type_uint64/3}).
v_type_uint64(N, _Path, _TrUserData) when 0 =< N, N =< 18446744073709551615 -> ok;
v_type_uint64(N, Path, _TrUserData) when is_integer(N) -> mk_type_error({value_out_of_range, uint64, unsigned, 64}, N, Path);
v_type_uint64(X, Path, _TrUserData) -> mk_type_error({bad_integer, uint64, unsigned, 64}, X, Path).

-compile({nowarn_unused_function,v_type_string/3}).
-dialyzer({nowarn_function,v_type_string/3}).
v_type_string(S, Path, _TrUserData) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
        B when is_binary(B) -> ok;
        {error, _, _} -> mk_type_error(bad_unicode_string, S, Path)
    catch
        error:badarg -> mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path, _TrUserData) -> mk_type_error(bad_unicode_string, X, Path).

-compile({nowarn_unused_function,mk_type_error/3}).
-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error, {Error, [{value, ValueSeen}, {path, Path2}]}}).


-compile({nowarn_unused_function,prettify_path/1}).
-dialyzer({nowarn_function,prettify_path/1}).
prettify_path([]) -> top_level;
prettify_path(PathR) -> lists:append(lists:join(".", lists:map(fun atom_to_list/1, lists:reverse(PathR)))).


-compile({nowarn_unused_function,id/2}).
-compile({inline,id/2}).
id(X, _TrUserData) -> X.

-compile({nowarn_unused_function,v_ok/3}).
-compile({inline,v_ok/3}).
v_ok(_Value, _Path, _TrUserData) -> ok.

-compile({nowarn_unused_function,m_overwrite/3}).
-compile({inline,m_overwrite/3}).
m_overwrite(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,cons/3}).
-compile({inline,cons/3}).
cons(Elem, Acc, _TrUserData) -> [Elem | Acc].

-compile({nowarn_unused_function,lists_reverse/2}).
-compile({inline,lists_reverse/2}).
'lists_reverse'(L, _TrUserData) -> lists:reverse(L).
-compile({nowarn_unused_function,'erlang_++'/3}).
-compile({inline,'erlang_++'/3}).
'erlang_++'(A, B, _TrUserData) -> A ++ B.




gpb_version_as_string() ->
    "4.19.5".

gpb_version_as_list() ->
    [4,19,5].

gpb_version_source() ->
    "file".
